
package jaxws.twoServices.client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Foo", targetNamespace = "http://twoServices.jaxws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Foo {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://twoServices.jaxws/", className = "jaxws.twoServices.client2.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://twoServices.jaxws/", className = "jaxws.twoServices.client2.EchoResponse")
    @Action(input = "http://twoServices.jaxws/Foo/echoRequest", output = "http://twoServices.jaxws/Foo/echoResponse")
    public int echo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
