
package jaxws.twoServices.client2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FooService", targetNamespace = "http://twoServices.jaxws/", wsdlLocation = "file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/jaxws/twoServices/work/services/war/WEB-INF/wsdl/FooService.wsdl")
public class FooService
    extends Service
{

    private final static URL FOOSERVICE_WSDL_LOCATION;
    private final static WebServiceException FOOSERVICE_EXCEPTION;
    private final static QName FOOSERVICE_QNAME = new QName("http://twoServices.jaxws/", "FooService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/jaxws/twoServices/work/services/war/WEB-INF/wsdl/FooService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FOOSERVICE_WSDL_LOCATION = url;
        FOOSERVICE_EXCEPTION = e;
    }

    public FooService() {
        super(__getWsdlLocation(), FOOSERVICE_QNAME);
    }

    public FooService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOOSERVICE_QNAME, features);
    }

    public FooService(URL wsdlLocation) {
        super(wsdlLocation, FOOSERVICE_QNAME);
    }

    public FooService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOOSERVICE_QNAME, features);
    }

    public FooService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FooService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Foo
     */
    @WebEndpoint(name = "foo")
    public Foo getFoo() {
        return super.getPort(new QName("http://twoServices.jaxws/", "foo"), Foo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Foo
     */
    @WebEndpoint(name = "foo")
    public Foo getFoo(WebServiceFeature... features) {
        return super.getPort(new QName("http://twoServices.jaxws/", "foo"), Foo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOOSERVICE_EXCEPTION!= null) {
            throw FOOSERVICE_EXCEPTION;
        }
        return FOOSERVICE_WSDL_LOCATION;
    }

}
