
package jaxws.twoServices.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BarService", targetNamespace = "http://twoServices.jaxws/", wsdlLocation = "file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/jaxws/twoServices/work/services/war/WEB-INF/wsdl/BarService.wsdl")
public class BarService
    extends Service
{

    private final static URL BARSERVICE_WSDL_LOCATION;
    private final static WebServiceException BARSERVICE_EXCEPTION;
    private final static QName BARSERVICE_QNAME = new QName("http://twoServices.jaxws/", "BarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/jaxws/twoServices/work/services/war/WEB-INF/wsdl/BarService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BARSERVICE_WSDL_LOCATION = url;
        BARSERVICE_EXCEPTION = e;
    }

    public BarService() {
        super(__getWsdlLocation(), BARSERVICE_QNAME);
    }

    public BarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BARSERVICE_QNAME, features);
    }

    public BarService(URL wsdlLocation) {
        super(wsdlLocation, BARSERVICE_QNAME);
    }

    public BarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BARSERVICE_QNAME, features);
    }

    public BarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Bar
     */
    @WebEndpoint(name = "bar")
    public Bar getBar() {
        return super.getPort(new QName("http://twoServices.jaxws/", "bar"), Bar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Bar
     */
    @WebEndpoint(name = "bar")
    public Bar getBar(WebServiceFeature... features) {
        return super.getPort(new QName("http://twoServices.jaxws/", "bar"), Bar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BARSERVICE_EXCEPTION!= null) {
            throw BARSERVICE_EXCEPTION;
        }
        return BARSERVICE_WSDL_LOCATION;
    }

}
