
package wsrm.roundtrip.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPing", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPing {


    /**
     * 
     * @param echoString
     * @return
     *     returns wsrm.roundtrip.server.PingResponseBodyType
     */
    @WebMethod(operationName = "EchoString")
    @WebResult(name = "echoStringResponse", targetNamespace = "http://tempuri.org/", partName = "echoStringResponse")
    public PingResponseBodyType echoString(
        @WebParam(name = "echoString", targetNamespace = "http://tempuri.org/", partName = "echoString")
        PingRequestBodyType echoString);

}
