
package wstrust.bearer.sts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISecurityTokenService", targetNamespace = "http://tempuri.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISecurityTokenService {


    /**
     * 
     * @param rstMessage
     * @return
     *     returns wstrust.bearer.sts.MessageBodyType
     */
    @WebMethod(operationName = "IssueToken", action = "http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue")
    @WebResult(name = "MessageBody", targetNamespace = "http://schemas.microsoft.com/Message", partName = "IssueTokenResult")
    public MessageBodyType issueToken(
        @WebParam(name = "MessageBody", targetNamespace = "http://schemas.microsoft.com/Message", partName = "rstMessage")
        MessageBodyType rstMessage);

}
