
package wstrust.bearer.sts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecurityTokenService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/wstrust/bearer/sts/sts.wsdl")
public class SecurityTokenService
    extends Service
{

    private final static URL SECURITYTOKENSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECURITYTOKENSERVICE_EXCEPTION;
    private final static QName SECURITYTOKENSERVICE_QNAME = new QName("http://tempuri.org/", "SecurityTokenService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/space/sources/ws-test-harness/trunk/test-harness/src/test/testcases/wstrust/bearer/sts/sts.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITYTOKENSERVICE_WSDL_LOCATION = url;
        SECURITYTOKENSERVICE_EXCEPTION = e;
    }

    public SecurityTokenService() {
        super(__getWsdlLocation(), SECURITYTOKENSERVICE_QNAME);
    }

    public SecurityTokenService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYTOKENSERVICE_QNAME, features);
    }

    public SecurityTokenService(URL wsdlLocation) {
        super(wsdlLocation, SECURITYTOKENSERVICE_QNAME);
    }

    public SecurityTokenService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYTOKENSERVICE_QNAME, features);
    }

    public SecurityTokenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityTokenService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISecurityTokenService
     */
    @WebEndpoint(name = "CustomBinding_ISecurityTokenService")
    public ISecurityTokenService getCustomBindingISecurityTokenService() {
        return super.getPort(new QName("http://tempuri.org/", "CustomBinding_ISecurityTokenService"), ISecurityTokenService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISecurityTokenService
     */
    @WebEndpoint(name = "CustomBinding_ISecurityTokenService")
    public ISecurityTokenService getCustomBindingISecurityTokenService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CustomBinding_ISecurityTokenService"), ISecurityTokenService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYTOKENSERVICE_EXCEPTION!= null) {
            throw SECURITYTOKENSERVICE_EXCEPTION;
        }
        return SECURITYTOKENSERVICE_WSDL_LOCATION;
    }

}
