#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-client

# clean the log
if [ -f log.txt ]; then
    mv log.txt log-`date +%Y-%m-%d_%H-%M-%S`.txt
fi;

. shared

G_STATUS=0
L_STATUS=0
<#if shutdownPorts??>
    <#list shutdownPorts as port>
wget http://127.0.0.1:${port}/stop > /dev/null 2>&1
    </#list>
</#if>

clean client-classes
clean client-source
clean services
clean ../mods
clean ../mods-server
clean deploy-source
clean deploy-classes
clean shared-source

