#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-client

G_STATUS=0
L_STATUS=0
<#if shutdownPorts??>
    <#list shutdownPorts as port>
wget http://127.0.0.1:${port}/stop
    </#list>
</#if>

echo "==================================================================== global variables ============"
echo "      G_STATUS=[$G_STATUS] ~ result so far of current testcase"
echo "         debug=[$debug] ~ silent / verbose mode"
echo "      failFast=[$failFast] ~ if true it won't continue with other tests for given webservice"
echo "     skipTests=[$skipTests] ~ run tests just up to deploy / all (inncluding client tests)"
echo "useNamedModule=[$useNamedModule] ~ run as unnamed module / named (including module-info.java)"
echo "=================================================================================================="

