#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-client

. shared

prolog $CTX

log "Running ${testName}"

if [ "$skipTests" != "true" ]; then

    # compile generated client sources
    SRC_FILES=
    if [ -d "client-source" ]; then
        SRC_FILES=`find client-source -name '*.java'`
        r javac -cp ${classpath} -d client-classes $SRC_FILES
    fi

    # compile generated bash.Client#.java
    r javac -cp ${classpath} -d client-classes \
         bsh/Client${stage}.java

    # actual running client
    runjava ${classpath} bsh.Client${stage}
    #r sleep 1
fi;