#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-client

if [ "$debug" = "true" ]; then
   echo == $CTX ========================================================
fi;

function r {
    if [ $G_STATUS -ne 0 ]; then
        return $G_STATUS;
    fi;
    if [ "$debug" = "true" ]; then
       #echo $CTX: $G_STATUS
       echo "$@"
       echo ""
       "$@"
    else
       echo "$@" >> log.txt 2>&1
       echo "" >> log.txt 2>&1
       "$@" >> log.txt 2>&1
    fi;

    local status=$?
    if [ $status -ne 0 ]; then
        G_STATUS=$status
        FAILED=$((FAILED+1))
        echo "FAILED: $CTX/$1"
        echo "FAILED: $CTX/$1" >> log.txt 2>&1
    fi
    return $status
}

r echo "Running ${testName}"

SRC_FILES=
if [ -d "client-source" ]; then
    SRC_FILES=`find client-source -name '*.java'`
    r javac -cp ${classpath} -d client-classes $SRC_FILES
fi

r javac -cp ${classpath} -d client-classes \
     bsh/Client${stage}.java

if [ "$skipTests" != "true" ]; then 
  r java -cp ${classpath} bsh.Client${stage}
  r sleep 1
fi;