#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
L_STATUS=0

if [ "$failFast" = "true" ]; then
    if [ "$G_STATUS" = "1" ]; then
       return 1
    fi;
fi;

SHARED_DIR=/Users/miran/dev/jaxws-ri/jaxws-ri/tests/unit/testcases-no-harness/SHARED/
SHARED_LIB=$SHARED_DIR/lib/jaxwsTestUtil.jar
CLIENT_CLASSPATH=${classpath}:$SHARED_LIB

function compileClientClasses() {
    DIR=$1
    SRC_FILES=
    if [ -d $DIR ]; then
        SRC_FILES=`find $DIR -name '*.java'`
        r javac -XDignore.symbol.file -cp $CLIENT_CLASSPATH -d client-classes $SRC_FILES
    fi
}

if [ "$skipTests" != "true" ]; then

    TOTAL_STEPS=$((TOTAL_STEPS+1))

    export CTX="${serviceId}:${stage}-client(${testName})"

    . shared

    prolog $CTX

    log "Running ${testName}"

    # compile generated client sources
    compileClientClasses "../src/junit"
    compileClientClasses "client-source"
    compileClientClasses "../src/common"
    compileClientClasses "../src/client"

    # copy resources
    if [ -d ../src/resources ]; then
        r cp -rv ../src/resources/* client-classes | true
    fi

    # compile generated bash.Client#.java
    r javac -XDignore.symbol.file -cp $CLIENT_CLASSPATH -d client-classes bsh/Client${stage}.java bsh/Util.java

    runjava $CLIENT_CLASSPATH bsh.Client${stage}
fi;

