#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
L_STATUS=0

if [ "$G_STATUS" = "1" ]; then
    return 1
fi;

TOTAL_STEPS=$((TOTAL_STEPS+1))

export CTX=${serviceId}:${stage}-deploy

. shared

prolog $CTX

export SVC_DIR=${serviceDirectory}

mkdirp services/$SVC_DIR/war/WEB-INF/wsdl/

cpwsdl "../src/$SVC_DIR/*.wsdl"
cpwsdl "../src/$SVC_DIR/*.xsd"

# handlers.xml, example: testcases/bugs/jaxws1015
cpclasses "../src/$SVC_DIR/*.xml"


r javac -cp ${classpath} bsh/Deploy${stage}.java

runjavabg \
    .:${classpath} \
    bsh.Deploy${stage}

r sleep 3