#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-deploy

if [ "$debug" = "true" ]; then
   echo == $CTX ========================================================
fi;

function r {
    if [ $G_STATUS -ne 0 ]; then
        return $G_STATUS;
    fi;
    if [ "$debug" = "true" ]; then
       #echo $CTX: $G_STATUS
       echo "$@"
       echo ""
       "$@"
    else
       echo "$@" >> log.txt 2>&1
       echo "" >> log.txt 2>&1
       "$@" >> log.txt 2>&1
    fi;

    local status=$?
    if [ $status -ne 0 ]; then
        G_STATUS=$status
        FAILED=$((FAILED+1))
        echo "FAILED: $CTX/$1"
    fi
    return $status
}

# copy wsdls ...
mkdir -p services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
cp ../src/server/*.wsdl services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
cp ../src/server/*.xsd services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true

r javac -cp ${classpath} bsh/Deploy${stage}.java

if [ $G_STATUS -ne 0 ]; then
   return $G_STATUS
fi;
    if [ "$debug" = "true" ]; then 
       echo "java -cp .:${classpath} bsh.Deploy${stage} &

"
       java $JAVA_OPTS -cp .:${classpath} bsh.Deploy${stage} &
    else
       echo "java -cp .:${classpath} bsh.Deploy${stage} &" >> log.txt 2>&1

       java $JAVA_OPTS -cp .:${classpath} bsh.Deploy${stage} >> log.txt 2>&1 &
    fi;
r sleep 3