#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
L_STATUS=0

if [ "$G_STATUS" = "1" ]; then
    return 1
fi;

TOTAL_STEPS=$((TOTAL_STEPS+1))

export CTX=${serviceId}:${stage}-deploy

. shared

prolog $CTX

export SVC_DIR=${serviceDirectory}

mkdirp services/$SVC_DIR/war/WEB-INF/wsdl/

<#if wsdlDocs??>
    <#list wsdlDocs as wsdl>
cpwsdl ../src/$SVC_DIR ${wsdl}
    </#list>
</#if>

<#if wsdlLocation??>
cpwsdl ../src/$SVC_DIR ${wsdlLocation}
mkdir -p services/$SVC_DIR/war/classes/WEB-INF
mv -v services/$SVC_DIR/war/WEB-INF/wsdl services/$SVC_DIR/war/classes/WEB-INF/
</#if>

# handlers.xml, example: testcases/bugs/jaxws1015
cpclasses "../src/$SVC_DIR/*.xml"

SHARED_DIR=/Users/miran/dev/jaxws-ri/jaxws-ri/tests/unit/testcases-no-harness/SHARED/
SHARED_LIB=$SHARED_DIR/lib/jaxwsTestUtil.jar
SERVER_CLASSPATH=${classpath}:$SHARED_LIB:.

r javac -cp ${classpath} bsh/Deploy${stage}.java

runjavabg $SERVER_CLASSPATH bsh.Deploy${stage}

r sleep 3