#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
L_STATUS=0

if [ "$G_STATUS" = "1" ]; then
    return 1
fi;

TOTAL_STEPS=$((TOTAL_STEPS+1))

export CTX=${serviceId}:${stage}-javac

. shared

prolog $CTX

<#list mkdirs as dir>
mkdirp ${dir}
</#list>

# to be sure the directory is there (used in classpath ...)
mkdirp client-classes

<#if classpath??>
CLIENT_CLASSPATH=${classpath}
</#if>
CLIENT_CLASSPATH=$CLIENT_CLASSPATH:$SHARED_LIB

# compile generated client sources
compileShared
#compileClientClasses "client-source"
compileClientClasses "../src/common"
#compileClientClasses "../src/client"

r javac \
<#list params as param>
        ${param} <#if param_has_next>\</#if>
</#list>
