#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-javac

. shared

prolog $CTX

<#list mkdirs as dir>
mkdirp ${dir}
</#list>

r javac \
<#list params as param>
        ${param} <#if param_has_next>\</#if>
</#list>
