#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-javac

if [ "$debug" = "true" ]; then
   echo == $CTX ========================================================
fi;

function r {
    if [ $G_STATUS -ne 0 ]; then
        return $G_STATUS;
    fi;
    if [ "$debug" = "true" ]; then
       #echo $CTX: $G_STATUS
       echo "$@"
       echo ""
       "$@"
    else
       echo "$@" >> log.txt 2>&1
       echo "" >> log.txt 2>&1
       "$@" >> log.txt 2>&1
    fi;

    local status=$?
    if [ $status -ne 0 ]; then
        G_STATUS=$status
        FAILED=$((FAILED+1))
        echo "FAILED: $CTX/$1"
    fi
    return $status
}

<#list mkdirs as dir>
r mkdir -p ${dir}
</#list>

r javac \
<#list params as param>
        ${param} <#if param_has_next>\</#if>
</#list>
