#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-run
# global testcase status
L_STATUS=0
export G_STATUS=0

cd ${workdir}

. shared

prolog $CTX

# clean the log
if [ -f log.txt ]; then
    mv log.txt log-`date +%Y-%m-%d_%H-%M-%S`.txt
fi;
rm -rf services
rm -rf server
rm -rf client-source
rm -rf client-classes

function logStepStatus() {
    if [ $L_STATUS -eq 0 ]; then
         TOTAL_PASSED=$((TOTAL_PASSED+1))
         echo "PASSED:  $TOTAL_PASSED. $CTX" >> $GLOBAL_LOG_PREFIX-passed-total.txt 2>&1
    else
         TOTAL_FAILED=$((TOTAL_FAILED+1))
         echo "FAILED:  $TOTAL_FAILED. $CTX" >> $GLOBAL_LOG_PREFIX-failed-total.txt 2>&1
    fi;
}

<#list scripts as script>
. ${script}
logStepStatus

</#list>

# ----------------------------------------------------
# undeploy
# ----------------------------------------------------
<#if shutdownPorts??>
    <#if  shutdownPorts?has_content>
if [ "$debug" = "true" ]; then
    <#list shutdownPorts as port>
    wget http://127.0.0.1:${port}/stop
    </#list>
else
    <#list shutdownPorts as port>
   wget http://127.0.0.1:${port}/stop >> log.txt 2>&1
    </#list>
fi;
    </#if>
</#if>

r sleep 1

# ----------------------------------------------------
# testcase result
# ----------------------------------------------------
if [ $G_STATUS -eq 0 ]; then
     echo "    OK: $CTX"
     PASSED=$((PASSED+1))
     echo "PASSED:  $PASSED. $CTX" >> $GLOBAL_LOG_PREFIX-passed.txt 2>&1
else
     echo "FAILED: ${serviceId}"
     FAILED=$((FAILED+1))
     echo "FAILED:  $FAILED. ${serviceId}" >> $GLOBAL_LOG_PREFIX-failed.txt 2>&1
fi;

