#!/bin/bash -ex
# service id: ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-run
# global testcase status
export G_STATUS=0

cd ${workdir}

. shared

prolog $CTX

# clean the log
rm -rf log.txt

<#list scripts as script>
. ${script}
</#list>

# ----------------------------------------------------
# undeploy
# ----------------------------------------------------
if [ "$debug" = "true" ]; then
   wget http://127.0.0.1:8888/stop
else
   wget http://127.0.0.1:8888/stop >> log.txt 2>&1
fi;

r sleep 1

# ----------------------------------------------------
# testcase result
# ----------------------------------------------------
if [ $G_STATUS -eq 0 ]; then
     echo "    OK: $CTX"
     PASSED=$((PASSED+1))
fi; 

