#!/bin/bash

function prolog() {
    if [ "$debug" = "true" ]; then
       echo == $1 ========================================================
    fi;
}

function log() {
    if [ "$debug" = "true" ]; then
       echo $1
    fi;
}

function r {
    if [ $G_STATUS -ne 0 ]; then
        return $G_STATUS;
    fi;
    if [ "$debug" = "true" ]; then
       #echo $CTX: $G_STATUS
       echo "$@"
       echo ""
       "$@"
    else
       echo "$@" >> log.txt 2>&1
       echo "" >> log.txt 2>&1
       "$@" >> log.txt 2>&1
    fi;

    local status=$?
    if [ $status -ne 0 ]; then
        G_STATUS=$status
        FAILED=$((FAILED+1))
        echo "FAILED: $CTX/$1"
    fi
    return $status
}

function mkdirp() {
    log "creating directory [$1]"
    mkdir -p $1 > /dev/null 2>&1 | true
}

function cpwsdl() {
    log "copying [$1] to [services/server/war/WEB-INF/wsdl/]"
    cp $1 services/server/war/WEB-INF/wsdl/ > /dev/null 2>&1 | true
}

function prepareModule() {
    MODULE=$1
    MODS=/Users/miran/dev/jigsaw/TESTS/JAXWS/unit/mods

    log "preparing module [$MODULE]"

    mkdir -p ../mods/
    cp -r $MODS/$MODULE ../mods/
    mkdir -p ../mods/$MODULE/bsh

    # SERVER
    if [ "$MODULE" = "server" ]; then
        cp -r services/server/war/WEB-INF/classes/* ../mods/$MODULE/
        cp -r bsh/Deploy*.class ../mods/$MODULE/bsh
        cp -r bsh/Endpoint*.class ../mods/$MODULE/bsh
    else
        cp -r client-classes/* ../mods/$MODULE/
        cp -r bsh/Client*.class ../mods/$MODULE/bsh
    fi;

    javac ../mods/$MODULE/module-info.java

}

function runjavabg() {
    CP=$1
    CLAZZ=$2
    MODULE=server
    J_OPTIONS="-cp $CP $CLAZZ"

    if [ "$useNamedModule" = "true" ]; then
        prepareModule $MODULE
        J_OPTIONS="-mp ../mods -m $MODULE/$CLAZZ"
        # nothing for cp mode
    fi;

    if [ "$debug" = "true" ]; then
       echo "java $JAVA_OPTS $J_OPTIONS &


       "
       java $JAVA_OPTS $J_OPTIONS &
    else
       echo "java $JAVA_OPTS $J_OPTIONS" >> log.txt 2>&1
       java $JAVA_OPTS $J_OPTIONS >> log.txt 2>&1 &
    fi;
}

function runjava() {
    CP=$1
    CLAZZ=$2
    MODULE=client
    J_OPTIONS="-cp $CP $CLAZZ"

    if [ "$useNamedModule" = "true" ]; then
        prepareModule $MODULE
        J_OPTIONS="-mp ../mods -m $MODULE/$CLAZZ"
        # nothing for cp mode
    fi;

    if [ "$debug" = "true" ]; then
       echo "java $JAVA_OPTS $J_OPTIONS"
       r java $JAVA_OPTS $J_OPTIONS
    else
       echo "java $JAVA_OPTS $J_OPTIONS" >> log.txt 2>&1
       r java $JAVA_OPTS $J_OPTIONS >> log.txt 2>&1
    fi;
}
