#!/bin/bash -ex
# service id:  ${serviceId}
# stage: ${stage}
if [ "$G_STATUS" = "1" ]; then
    return 1
fi;

TOTAL_STEPS=$((TOTAL_STEPS+1))

export CTX=${serviceId}:${stage}-tool

. shared

prolog $CTX

<#list dirs as dir>
mkdirp ${dir}
</#list>

r <#list params as param>      ${param} <#if param_has_next>\</#if>
</#list>

