#!/bin/bash -ex
# service id:  ${serviceId}
# stage: ${stage}
export CTX=${serviceId}:${stage}-tool

. shared

prolog $CTX

<#list dirs as dir>
mkdirp ${dir}
</#list>

r <#list params as param>      ${param} <#if param_has_next>\</#if>
</#list>

