
package jaxws.fromjava_handlers.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13579
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddNumbers", targetNamespace = "http://server.fromjava_handlers/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddNumbers {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws AddNumbersException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNumbers", targetNamespace = "http://server.fromjava_handlers/", className = "jaxws.fromjava_handlers.client.AddNumbers_Type")
    @ResponseWrapper(localName = "addNumbersResponse", targetNamespace = "http://server.fromjava_handlers/", className = "jaxws.fromjava_handlers.client.AddNumbersResponse")
    @Action(input = "http://server.fromjava_handlers/AddNumbers/addNumbersRequest", output = "http://server.fromjava_handlers/AddNumbers/addNumbersResponse", fault = {
        @FaultAction(className = AddNumbersException_Exception.class, value = "http://server.fromjava_handlers/AddNumbers/addNumbers/Fault/AddNumbersException")
    })
    public int addNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws AddNumbersException_Exception
    ;

}
